name: Unity Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger when a version tag is pushed


env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest  # Using Windows as it was the last used OS for editing.

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: game-ci/unity-builder@v4.3.0
        with:
          unityVersion: 2021.3.5f1
          targetPlatform: StandaloneWindows64
          projectPath: ./XMarksTheSpot